### ISSUE TITLE
how use subtitle?

### ISSUE THREAD

**Issue by GeoXTen** [0Xiaohei0/VoiceToJapanese#11]
how setup subtitle ?

**Comment by GeoXTen** [comment]
now i know but sometimes the transelator doesnt't work

**Comment by 0Xiaohei0** [comment]
There has been an issue with server cost, so I have to shut down the speech to text service for now. Text input should still work. Also, alpha1 and alpha2 are on the free plan so they should still work as well.

**Comment by GeoXTen** [comment]
Aww :(

**Comment by 0Xiaohei0** [comment]
There will be. But I need to rewrite speech to text to run locally. Until that's done, you can try the subtitler here: https://youtu.be/bN5UaEkIPGM , or here: https://github.com/MotazSabri/Hanami-release?ref=producthunt
