### ISSUE TITLE
Cannot construct SpeechConfig with the given arguments

### ISSUE THREAD

**Issue by Rempacious** [0Xiaohei0/VoiceToJapanese#2]
![image](https://user-images.githubusercontent.com/73411987/223524995-0ecf045c-095c-406c-91a8-e617815fdf5e.png)

Encountered this error, do you need subscription for Azure services?

**Comment by 0Xiaohei0** [comment]
I have compiled the python file into a .exe that you can just download and run. It's in the release section (https://github.com/0Xiaohei0/VoiceToJapanese/releases).  I has all the required api keys built in so you shouldn't have any issues.
If you still want to run the console project without using Azure tts, you can set use_microsoft_azure_tts and repeat_in_chinese to false and this should skip all the azure code.

**Comment by Rempacious** [comment]
The UI executable now properly works. Thank you very much!
