### ISSUE TITLE
no module ´customtkinter´

### ISSUE THREAD

**Issue by pizzamh** [0Xiaohei0/VoiceToJapanese#26]
![Captura](https://github.com/0Xiaohei0/VoiceToJapanese/assets/66393945/ccfa3db0-2e90-415d-be99-89f10ad74b3a)

**Comment by goenyan** [comment]
Use the exe version instead.
https://github.com/0Xiaohei0/VoiceToJapanese/tree/v1.2.3

**Comment by pizzamh** [comment]
the problem continues with 'customtkinter'

![imagen](https://github.com/0Xiaohei0/VoiceToJapanese/assets/66393945/6e9df3f5-584d-493c-9168-c99b27b5df2f)

**Comment by goenyan** [comment]
Then try go to the "files" folder, run cmd then run this command "python ui.py"

**Comment by pizzamh** [comment]
I have this problem when executing this code pip install -r requirements.txt or at least from what I see

![imagen](https://github.com/0Xiaohei0/VoiceToJapanese/assets/66393945/0ac71f2f-d4cc-4e1c-b2e3-6e67f252a7ec)

Is it normal for it to end like this?

**Comment by 0Xiaohei0** [comment]
Use python 3.10![image](https://github.com/0Xiaohei0/VoiceToJapanese/assets/24196833/903cdf4d-2222-4273-8127-e8d466b6d485)

**Comment by pizzamh** [comment]
Thanks, I thought there would be no problem with the version difference

![Captura](https://github.com/0Xiaohei0/VoiceToJapanese/assets/66393945/523f403c-e07f-4af7-be61-f0908f8d2128)
