### ISSUE TITLE
Decoding error?

### ISSUE THREAD

**Issue by akanevr** [0Xiaohei0/VoiceToJapanese#29]
Not exactly sure what's happened. If I do a setup everything works fine without any issues, but if I close the program and try to work with it again I get the following error:

`Sending POST request to: https://api.elevenlabs.io/v1/text-to-speech/
<Response [404]>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\akane\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "E:\Alice\UI-v1.2.4-py\files\.venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "E:\Alice\UI-v1.2.4-py\files\UI.py", line 339, in synthesizeButton_callback
    STTS.start_TTS_pipeline(self.text_input.get("1.0", customtkinter.END))
  File "E:\Alice\UI-v1.2.4-py\files\STTSLocal.py", line 457, in start_TTS_pipeline
    syntheize_audio(
  File "E:\Alice\UI-v1.2.4-py\files\STTSLocal.py", line 227, in syntheize_audio
    elevenlab_synthesize(text)
  File "E:\Alice\UI-v1.2.4-py\files\STTSLocal.py", line 264, in elevenlab_synthesize
    audio_content = AudioSegment.from_file(
  File "E:\Alice\UI-v1.2.4-py\files\.venv\lib\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version N-109960-g3153c441e1-20230303 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230303
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.100 / 60.  6.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[cache @ 0000023b23449bc0] Inner protocol failed to seekback end : -40
    Last message repeated 1 times
[mp3 @ 0000023b23449600] Failed to read frame size: Could not seek to 1045.
[cache @ 0000023b23449bc0] Statistics, cache hits:2 cache misses:1
cache:pipe:0: Invalid argument`

Not sure what I did wrong or if I shutdown wrong.

**Comment by 0Xiaohei0** [comment]
eleven lab did not return a proper response, maybe check your api key in settings

**Comment by akanevr** [comment]
I am 100% silly and you are correct, seems the api key was empty. Failed to check it.

100% great job on this thank you for your quick response!
