### ISSUE TITLE
Error when opening start.bat and setup.bat

### ISSUE THREAD

**Issue by Xandathemanda** [0Xiaohei0/VoiceToJapanese#30]
The system cannot find the path specified.
C:\Users\lilbr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: can't open file 'C:\\Users\\lilbr\\Downloads\\UI.py': [Errno 2] No such file or directory

PLEASE HELP PYTHON IS ALWAYS THE PROBLEM WITH EVERY TUTORIAL I FOLLOW PLEASEEEEEEEEEEEEEEE

**Comment by akanevr** [comment]
Have you installed the right python distro? It needs to be 3.10.

**Comment by 0Xiaohei0** [comment]
There is a exe version in 1.2.3 that you can try. About the error:"can't open file 'C:\Users\lilbr\Downloads\UI.py" It's trying to run UI.py in your downloads folder, you are likely running the script in the wrong directory.

**Comment by Xandathemanda** [comment]
> There is a exe version in 1.2.3 that you can try. About the error:"can't open file 'C:\Users\lilbr\Downloads\UI.py" It's trying to run UI.py in your downloads folder, you are likely running the script in the wrong directory.

You removed the exe version from the github bro otherwise i wouldve done that already
