### ISSUE TITLE
Speech to text API quota issue

### ISSUE THREAD

**Issue by 0Xiaohei0** [0Xiaohei0/VoiceToJapanese#4]
![image](https://user-images.githubusercontent.com/24196833/223913577-df0cae05-5a9c-4343-b82c-56cf1ec25ea6.png)
There is a known issue where after pressing the record button,  no audio input gets captured. This is caused by the a limit set by microsoft tts that only allows one concurrent request. If someone else is in the process of recording, your request will be canceled. I plan to solve this problem by upgrading to a paid plan. I will implement the solution and post the build with updated API keys as soon as possible.

**Comment by Rempacious** [comment]
Are there any ways to donate for the paid plan? Your work is really great.

**Comment by 0Xiaohei0** [comment]
I'll consider opening donations if the server cost is significant. Feel free to make videos about this, though the project isn't quite ready yet.

**Comment by 0Xiaohei0** [comment]
New build should fix this issue https://github.com/0Xiaohei0/VoiceToJapanese/releases/tag/Alpha2
