### ISSUE TITLE
Ui.exe error

### ISSUE THREAD

**Issue by Rennorijin** [0Xiaohei0/VoiceToJapanese#8]
![Screenshot (65)](https://user-images.githubusercontent.com/127474559/224259438-1e17e36e-d49e-4e59-86c7-5ecadd0b83a7.png)

Getting this issue when I try to run Ui.exe

**Comment by 0Xiaohei0** [comment]
Did you screenshot all the text in the error window? There should be an error code further down. Can you try enlarging the error window and screenshot the whole thing?

**Comment by Rennorijin** [comment]
Yeah nvm, I fixed it when I enabled SVM Mode in the bios. It was a docker desktop issue, it works now.
